@CityInfo_HostAddress = http://localhost:5288

GET {{CityInfo_HostAddress}}/api/cities
Accept: application/json

###
GET {{CityInfo_HostAddress}}/api/citiesss
Accept: application/json

###
GET {{CityInfo_HostAddress}}/api/cities/1 
Accept: application/json

###
GET {{CityInfo_HostAddress}}/api/cities/10 
Accept: application/json

###
GET {{CityInfo_HostAddress}}/api/cities/1/pointsofinterest
Accept: application/json

###
GET {{CityInfo_HostAddress}}/api/cities/1/pointsofinterest/1
Accept: application/json

###
POST {{CityInfo_HostAddress}}/api/cities/3/pointsofinterest
Accept: application/json
Content-Type: application/json
{ "name": "Pere Lachaice", "description": "Famous cemetery where Jim Morrison are buried." }


###
GET {{CityInfo_HostAddress}}/api/cities/3/pointsofinterest/9
Accept: application/json